services:
  c1-db:
    image: mariadb:11
    container_name: c1-db
    environment:
      MARIADB_DATABASE: c1_wp
      MARIADB_USER: wp
      MARIADB_PASSWORD: wp123
      MARIADB_ROOT_PASSWORD: root123
    volumes:
      - c1_db_data:/var/lib/mysql
    networks:
      - c1_net
    restart: unless-stopped

  c1-wp:
    image: wordpress:6-apache
    container_name: c1-wp
    depends_on:
      - c1-db
    environment:
      WORDPRESS_DB_HOST: c1-db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp123
      WORDPRESS_DB_NAME: c1_wp
      # IMPORTANTE: escapar $ para não virar variável do Compose
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','https://www.bolachaekernel.com/cms');
        define('WP_SITEURL','https://www.bolachaekernel.com/cms');
        if (isset($$_SERVER['HTTP_X_FORWARDED_HOST'])) { $$_SERVER['HTTP_HOST'] = $$_SERVER['HTTP_X_FORWARDED_HOST']; }
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') { $$_SERVER['HTTPS'] = 'on'; }
        define('FORCE_SSL_ADMIN', true);
    volumes:
      - c1_wp_data:/var/www/html
    networks:
      - c1_net
    restart: unless-stopped

  c1-proxy:
    build:
      context: ./Containers/PROXY
      dockerfile: Dockerfile
    image: c1-proxy
    container_name: c1-proxy
    depends_on:
      - c1-wp
    networks:
      - kernelenet
      - c1_net
    volumes:
      - ./Containers/PROXY/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Containers/PROXY/conf/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./Containers/PROXY/portal:/usr/share/nginx/html:ro
    restart: unless-stopped

networks:
  kernelenet:
    external: true
    name: kernelenet
  c1_net: {}

volumes:
  c1_db_data:
  c1_wp_data:
